name: CI

on:
  push:
    branches:
    - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Request Block
      id: block
      uses: Satak/webrequest-action@v1.2.2
      with:
        url: https://api.etherscan.io/api?module=proxy&action=eth_blockNumber&apikey=${{ secrets.ETHERSCAN_KEY }}
        method: GET
     
    - name: Parse
      id: parser
      run: |
        $output = '${{ steps.block.outputs.output }}' | ConvertFrom-Json
        Write-Host "Time from output $($output.time) statusCode $($output.statusCode) data $($output.data)"
      shell: pwsh
  
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'

    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
          
    - run: npm ci

    - name: Build
      run: |
        $output1 = ${{ steps.block.outputs.output.data.result }}
        echo $output1
    
    - name: Upload to IPFS
      uses: aquiladev/ipfs-action@v0.1.1
      id: upload
      with:
        path: ./build
        verbose: true
